name: Deploy React App to FTP
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

# Environment variables available to all jobs and steps in this workflow
env:
  FTP_SERVER: ${{ secrets.FTP_SERVER }} # secret containing deployment token for your static web app
  FTP_USER: ${{ secrets.FTP_USER }} # secret containing deployment token for your static web app
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # secret containing deployment token for your static web app



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the React app
        run: npm run build
      
      #- name: Ping the server
        #run: ping -c 5 educacional.org.ar
        
      - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # ftp server
          server: FTP_SERVER
          # ftp username
          username: FTP_USER
          # ftp password
          password: FTP_PASSWORD
          # Folder to upload from, must end with trailing slash /
          local-dir: ./dist/ # optional
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: ./ # optional
